PAAS-1230: replace hardcoded values by envvar in jahia.properties
Jahia/paas_jelastic_dx_universal pull request #145
Opened 2020-11-23 23:59 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1230

Short description:
**installMaven** step has been removed because it is enabled anyways in **jahiastic-jahia** Docker image (regardless of the environment type, prod or dev)

2020-11-26 09:34 UTC, laurentfufu requested changes

2020-11-26 09:34 UTC, laurentfufu commented on jahia/jahia_actions.yml
> +            MANAGER_PASSWORD: ${response.out}
probably lacking of coffee but I don't get it
is 168-172 block required ?

2020-11-26 09:34 UTC, laurentfufu commented on jahia/jahia_actions.yml
> +            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_proc: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_prod_proc}
```suggestion
    - if (settings.mode == "production"):
        - setGlobals:
            jahia_cfg_org_jahia_ehcachemanager_maxBytesLocalHeap: ${globals.org_jahia_ehcachemanager_maxBytesLocalHeap_prod}
            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_cp: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_prod_cp}
            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_proc: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_prod_proc}
    - else:
        - setGlobals:
            jahia_cfg_org_jahia_ehcachemanager_maxBytesLocalHeap: ${globals.org_jahia_ehcachemanager_maxBytesLocalHeap_dev}
            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_cp: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_dev}
            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_proc: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_dev}
```

will sound more readable to me

2020-11-26 13:57 UTC, adoux commented on jahia/jahia_actions.yml
> +            MANAGER_PASSWORD: ${response.out}
Oops, my mistake, should have removed "cp" from line 165, let me fix that.

2020-11-26 14:07 UTC, adoux commented on jahia/jahia_actions.yml
> +            jahia_cfg_org_jahia_ehcachemanager_big_maxBytesLocalHeap_proc: ${globals.org_jahia_ehcachemanager_big_maxBytesLocalHeap_prod_proc}
Fixed

2020-11-26 14:55 UTC, laurentfufu requested changes

2020-11-26 14:55 UTC, laurentfufu commented on jahia/jahia_actions.yml
> +            MANAGER_PASSWORD: ${response.out}
with this, the MANAGER_PASSWORD for cp group will only match the last `foreach` node hash.

Maybe we should generate the hash only on proc, and then set MANAGER_PASSWORD on proc and cp groups, then update the properties file on cp group nodes

2020-11-26 19:44 UTC, adoux commented on jahia/jahia_actions.yml
> +            MANAGER_PASSWORD: ${response.out}
Fixed!

2020-11-26 19:45 UTC, adoux commented
Please promise that was your last change request @laurentfufu :pleading_face:

2020-11-30 13:21 UTC, laurentfufu approved these changes

2020-11-30 13:21 UTC, merged