PASS-1296: Create Vault envvars on haproxy nodes
Jahia/paas_jelastic_dx_universal pull request #146
Opened 2020-11-25 22:31 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1296

Short description:
Create Vault envvars on haproxy nodes at env installation

2020-11-26 07:31 UTC, kevinvandel requested changes

2020-11-26 07:31 UTC, kevinvandel commented on install.yml
> +  vault_clusterurl: ${settings.vaultClusterUrl}
The settings need to be declared under `settings:` (at the end of the file)
(note: they need to be declared as "required")

2020-11-26 10:18 UTC, laurentfufu requested changes

2020-11-26 10:18 UTC, laurentfufu commented on install.yml
> +  vault_clusterurl: ${settings.vaultClusterUrl}
about the `required`, maybe we shouldn't while the front don't sent them ?

2020-11-26 10:25 UTC, kevinvandel commented on install.yml
> +  vault_clusterurl: ${settings.vaultClusterUrl}
Damn, good point !
So either we do it in two steps (2 PR), or we merge this PR and the one on the frontend side at the same time (may not be easy to synchronize)

2020-11-26 20:52 UTC, amitc-jahia commented on install.yml
> +  vault_clusterurl: ${settings.vaultClusterUrl}
Requested changes have been made. The settings have been declared under `settings`. Please Review.

2020-11-27 07:40 UTC, kevinvandel approved these changes

2020-11-27 22:25 UTC, laurentfufu approved these changes

2020-11-30 10:03 UTC, merged