PAAS-1170: Use vault to fetch haproxy configurations
Jahia/paas_jelastic_dx_universal pull request #158
Opened 2020-12-14 23:53 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1170

Short description:

2020-12-15 12:37 UTC, Ronan-Gorain requested changes

2020-12-15 12:37 UTC, Ronan-Gorain commented on utils/rewrite-rules.yml
> +        if (! rpm --quiet -q jq);
As (now) mentioned in https://jira.jahia.org/browse/PAAS-1170 , the token and the vault hostname are not provided by the front. They already exists on bl as env var for the haproxy user, and in /.jelenv for root user.
The token can be fetched with something like this (didn't test)
`
source /.jelenv
token=$(curl  -XPOST https://$VAULT_CLUSTER_URL/v1/auth/approle/login --data '{"secret_id": "$VAULT_SECRET_ID", "role_id": "$VAULT_ROLE_ID"}' |jq -r .auth.client_token)`

2020-12-15 12:37 UTC, Ronan-Gorain commented on utils/rewrite-rules.yml
> +            mv "${globals.haproxy_backup_file}" "${globals.haproxy_frontend_file}"
We still need to return an error with the haproxy reload error output as it was done in the previous version

2020-12-15 22:49 UTC, amitc-jahia commented
Requested Changes have been made. Please review.

2020-12-16 13:03 UTC, laurentfufu requested changes

2020-12-16 13:03 UTC, laurentfufu commented on utils/rewrite-rules.yml
> +        echo "$(awk -v rewriterules="$rewrite_rules" '/START_REWRITES/{print;print rewriterules;next}1' ${globals.haproxy_frontend_file})" > "${globals.haproxy_frontend_file}"
they are a limits to a command line set at kernel level and that seems to be 2 MiB for _argv_ these days
so not sure it's a god id to use shell variable for potentially huge data

2020-12-16 13:14 UTC, Ronan-Gorain requested changes

2020-12-16 13:29 UTC, laurentfufu commented on utils/rewrite-rules.yml
> +        echo "$(awk -v rewriterules="$rewrite_rules" '/START_REWRITES/{print;print rewriterules;next}1' ${globals.haproxy_frontend_file})" > "${globals.haproxy_frontend_file}"
didn't read the awk because of my previous comment but you right indeed

2020-12-16 21:09 UTC, amitc-jahia commented
Following Changes made as requested :

1. Instead of using shell variable, the response from curl is dumped into a file and using the file to read the rules.
2. Using sed with expression script to remove all the content between the 2 markers and add the contents of rules file in between the markers.

Please review.

2020-12-17 13:35 UTC, Ronan-Gorain commented
Seems good to me but I'm not good enough to understand your sed command :) I'll let Laurent validate

2020-12-17 14:08 UTC, Ronan-Gorain approved these changes

2020-12-17 16:45 UTC, laurentfufu approved these changes

2020-12-17 16:45 UTC, merged