PAAS-1322: Remove envLink on Jahia env deletion
Jahia/paas_jelastic_dx_universal pull request #163
Opened 2020-12-24 00:19 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1322

Short description:

2020-12-28 10:06 UTC, kevinvandel requested changes

2020-12-28 10:06 UTC, kevinvandel commented on install.yml
> +          envs = jelastic.env.control.GetNodeGroups(envName, session).object.filter(function (object) {
Shouldn't this be run on "jcustomer_env" instead of "envName" ?

2020-12-28 10:06 UTC, kevinvandel commented on install.yml
> +        jcustomer_env = jelastic.env.control.GetNodeGroups(envName, session).object.filter(function (object) {
It would be nice to keep it to camelCase (or at least not mixing different cases, but since this is JavaScript camelCase would be better)

2020-12-29 22:46 UTC, amitc-jahia commented
Changes made. Please review again.

2020-12-29 23:26 UTC, adoux submitted a review, later dismissed

2020-12-30 09:35 UTC, kevinvandel requested changes

2020-12-30 09:35 UTC, kevinvandel commented on install.yml
> +        if (jCustomerEnv != null) {
To avoid having a useless `else` block, here we can do this:
```
        if (jCustomerEnv == null) {
          return {"result": 0, "out": "No jCustomer env linked"};
        }
```
And continue without any `else` block (useless because of the `return` statement).

Generally speaking, this is a best practice to check particular cases like that. This avoids having a lot of `if` blocks piling up until we get to the "standard" case, and a cascade of `else` blocks at the end handling particular cases.

2020-12-30 09:35 UTC, kevinvandel commented on install.yml
> +            removedEnv = envsLinkedArr.splice(envsLinkedArr.indexOf[envName], 1);
This doesn't work at all because you used square brackets instead of parentheses. Did you really test it ? It took me 30 seconds with JSFiddle to see that nothing was working as expected.
```suggestion
            removedEnv = envsLinkedArr.splice(envsLinkedArr.indexOf(envName), 1);
```

2020-12-30 09:35 UTC, kevinvandel commented on install.yml
> +            removedEnv = envsLinkedArr.splice(envsLinkedArr.indexOf[envName], 1);
Also, we need to check `envsLinkedArr` really contains `envName` (i.e. index isn't `-1`), even though it shouldn't happen. But if for whatever reason we have an issue and the Jahia environment was not present in the jCustomer environment `envLink`, this script will randomly remove the last item of the `envLink` list, causing even more trouble (that we will probably have a hard time figuring out).

2020-12-30 09:35 UTC, kevinvandel commented on install.yml
> +          }
We can avoid duplicating code like this (also fixes indenting issue):
```suggestion
            newEnvLink = String(envsLinkedArr);
          } else {
            newEnvLink = null;
          }
          resp = jelastic.env.control.ApplyNodeGroupData(jCustomerEnv, session, nodeGroup='cp', data={'envLink': newEnvLink});
          return {"result": 0, "out": "Jahia env " + envName + " removed from envLink of " + jCustomerEnv};
```

2020-12-30 09:49 UTC, kevinvandel commented on install.yml
> +          if (envsLinked.indexOf(",") != -1) {
It could be nice to add a little comment here, because the `indexOf(",")` is not really explicit, especially if you don't have in mind that on jCustomer side the `envLink` can be a comma-separated list.

2020-12-30 22:28 UTC, amitc-jahia commented
Following changes made as requested : 

- Replaced the square brackets with parenthesis
- Added `if` condition to check whether jCustomer is `null` and continue without `else` block if condition is not met
- Check for the `envName` if present in the `envsLinked` of jCustomer
- Removed duplication of code
- Added comment to highlight that envLink on jCustomer side can contain multiple Jahia envs

Please review.

2020-12-31 07:37 UTC, kevinvandel requested changes

2020-12-31 07:37 UTC, kevinvandel commented on install.yml
> +          removedEnv = envsLinkedArr.splice(envsLinkedArr.indexOf(envName), 1);
`removedEnv` is never used, it can be removed:
```suggestion
          envsLinkedArr.splice(envsLinkedArr.indexOf(envName), 1);
```

2020-12-31 07:37 UTC, kevinvandel commented on install.yml
> +            newEnvLink = null;
Indenting issue (4 spaces here, while you use 2 spaces everywhere else)

2020-12-31 07:37 UTC, kevinvandel commented on install.yml
> +        if (envsLinked.indexOf(",") != -1) {      // envLink can contain multiple Jahia envs on jCustomer side
To avoid having an inline comment on the same line as the `if`, could you please put it on a new line before the `if` ?
Also in the comment it would be nice to specify that in this case values are separated with commas (so that we clearly understand the `indexOf(",")` thing).

2020-12-31 14:43 UTC, amitc-jahia commented
Changes made as requested. Please review.

2020-12-31 15:08 UTC, kevinvandel approved these changes

2020-12-31 15:08 UTC, merged