PAAS-1317: upgrade healthcheck
Jahia/paas_jelastic_dx_universal pull request #182
Opened 2021-01-28 15:47 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1317

Short description:

2021-01-28 17:50 UTC, laurentfufu requested changes

2021-01-28 17:50 UTC, laurentfufu commented on jahia/jahia-upgrade-healthcheck.yml
> +
not sure about this file, is this only a collection of actions to use through a mixins or did it should also be a standalone manifest ?
either "onInstall" and "settings" are missing or this header is too much.

2021-01-28 17:58 UTC, laurentfufu commented on jahia/jahia-upgrade-healthcheck.yml
> +
also, and maybe I'm totally wrong about this idea but maybe is ok to use a specific commit of https://github.com/Jahia/cloud-scripts/blob/master/jahia/mixins-jahia.yml since this is done as part of a migration.
this would avoid duplicating code between this repo and cloud-script and having a file here that may never be used again.

2021-01-29 08:09 UTC, Ronan-Gorain commented on jahia/jahia-upgrade-healthcheck.yml
> +
No, that's better indeed.

2021-01-29 09:33 UTC, Ronan-Gorain commented on jahia/jahia-upgrade-healthcheck.yml
> +
I removed the quoted lines to make this file a collection of actions.
After discussion, @kevinvandel do not want to include things from cloud-scripts into this repos so I left it like that.

2021-01-29 11:26 UTC, kevinvandel commented on jahia/jahia-upgrade-healthcheck.yml
> +
You make it sound like this is totalitarianism...

2021-01-29 15:43 UTC, laurentfufu commented on jahia/jahia-upgrade-healthcheck.yml
> +
For a migration manifest, I think it's not unreasonable to point to a specific commit of our "tools box" repo because the migration depend of a given time window and most (or all) `jahia/jahia-upgrade-healthcheck.yml`'s actions  seems to be copy/past from what we already have their.
So yeah it sound like totalitarianism :trollface:

2021-02-01 10:25 UTC, kevinvandel commented on jahia/jahia-upgrade-healthcheck.yml
> +    - if ("${this.healthcheckVersion}" == ""):
Couldn't we use "this" instead of relying on a global variable ? (not sure what is the least ugly...)

2021-02-01 10:29 UTC, kevinvandel commented on jahia/jahia-upgrade-healthcheck.yml
> +  startupJahiaHealthCheck:
This conflicts with another action with the same name (in jahia_actions)

2021-02-01 14:25 UTC, kevinvandel approved these changes

2021-02-01 14:38 UTC, laurentfufu approved these changes

2021-02-01 14:38 UTC, merged