PAAS-1208 fix a lot of stuff
Jahia/paas_jelastic_dx_universal pull request #185
Opened 2021-02-03 16:38 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1208

Short description:

2021-02-03 22:10 UTC, adoux requested changes

2021-02-03 22:10 UTC, adoux commented on migrations/v3/migration-to-v3.yml
> +    - environment.control.SetContainerEnvVars [proc, cp]:
I think it won't be okay cause it's for specific nodeId and it's still *set*, I think the right API call is `addContainerEnvVars`
Sorry bout that :see_no_evil: (should have reviewed earlier today)

2021-02-04 08:54 UTC, laurentfufu commented on migrations/v3/migration-to-v3.yml
> +    - environment.control.SetContainerEnvVars [proc, cp]:
I don't know what happen in my mind on this :grin:

2021-02-04 14:07 UTC, adoux approved these changes

2021-02-04 14:07 UTC, merged