PAAS-1458 add jexperience update for migration v4
Jahia/paas_jelastic_dx_universal pull request #225
Opened 2021-03-10 19:02 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1458

Short description:

2021-03-11 12:18 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        higher: 666.666.666.666
wtf ?!

2021-03-11 12:22 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        wget -qO "$MODULE_PATH" "$MODULE_URL"
I'm pretty sure doing only this will cause issues. I think we need to do like we did for healthcheck module: uninstall the previous version.
Maybe @Ronan-Gorain knows more about this (but I guess if we did that for the healthcheck module, it was not for the fun of it).

2021-03-11 12:37 UTC, Ronan-Gorain commented on migrations/v4/migration-to-v4.yml
> +        wget -qO "$MODULE_PATH" "$MODULE_URL"
I just did what I was told :) 
I don't know about consequences of not uninstalling the old module

2021-03-11 13:17 UTC, kevinvandel requested changes

2021-03-11 13:17 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        wget -qO "$MODULE_PATH" "$MODULE_URL"
Discussed with the support team, it is known to cause issues when Jahia is restarted (and we had the issue recently with a Cloud customer). It also makes restart/redeploy take more time.

So in the end we need to do exactly like for the healthcheck module:
- uninstall the older version(s) after the new one is started
- perform the operation on cp nodes too after it's done on proc (because propagation doesn't work on older versions of Jahia)

2021-03-11 18:03 UTC, laurentfufu commented on migrations/v4/migration-to-v4.yml
> +        higher: 666.666.666.666
evil is gone now

2021-03-11 18:05 UTC, laurentfufu commented on migrations/v4/migration-to-v4.yml
> +        wget -qO "$MODULE_PATH" "$MODULE_URL"
ok I will have a look on the artillery needed for that

2021-03-12 07:24 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        wget -qO "$MODULE_PATH" "$MODULE_URL"
I think you have everything in `jahia-upgrade-healthcheck.yml` (especially in `installNewHealthcheckIfNotPresent` and `removeOldHealthCheckVersions` actions)

2021-03-15 08:48 UTC, kevinvandel requested changes

2021-03-15 08:48 UTC, kevinvandel commented on jahia/jahia-module-management.yml
> +        log: None Active(s) ${globals.moduleName} module(s) deleted on ${this}
"none" = "aucun", but I suppose it's not what you want to say.
```suggestion
        log: Non-active "${globals.moduleName}" module(s) deleted on "${this}"
```

2021-03-15 08:48 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        bfile: ${response.out}
What does "bfile" mean ?

2021-03-15 08:50 UTC, kevinvandel commented on jahia/jahia-module-management.yml
> +        ${globals.karafConsole} bundle:list | awk ${globals.awkIC} ${globals.awkFS} \
On one hand I really don't like to rely on globals everywhere (the more we have actions defining globals, the more we risk names collision that could cause weird issue), but on the other hand I don't think we really have a choice with Cloud Scripting...

2021-03-15 16:07 UTC, laurentfufu commented on migrations/v4/migration-to-v4.yml
> +        bfile: ${response.out}
it was for "bundle.info file" and i found that funny because if you swap... well nevermind :trollface: 
i change this name to `gotJexperienceBundleInfo`

2021-03-15 16:09 UTC, laurentfufu commented on jahia/jahia-module-management.yml
> +        log: None Active(s) ${globals.moduleName} module(s) deleted on ${this}
disappeared since

2021-03-15 16:24 UTC, kevinvandel commented on jahia/jahia-module-management.yml
> +        log: None Active(s) ${globals.moduleName} module(s) deleted on ${this}
RIP

2021-03-15 16:24 UTC, kevinvandel commented on migrations/v4/migration-to-v4.yml
> +        bfile: ${response.out}
> if you swap

OK I got it, didn't see it the first time :sweat_smile:

2021-03-15 16:25 UTC, kevinvandel approved these changes

2021-03-15 16:49 UTC, Ronan-Gorain requested changes

2021-03-15 16:49 UTC, Ronan-Gorain commented on jahia/jahia_actions.yml
> +    - if("${globals.isKarafLoginEnabled}" == "true"):
A global might not be appropriate here because the action scope may not be.
If you want to enable karaf login on two nodes successively, you can't for the second because this global will already be set to true.
A local connection check or something like that may be more appropriate and can work if the package crash in the middle of the execution.

2021-03-15 16:49 UTC, Ronan-Gorain commented on jahia/jahia_actions.yml
> +    - if("${globals.isKarafLoginEnabled}" == "false"):
Same here about the global

2021-03-15 16:49 UTC, Ronan-Gorain commented on utils/compare-versions.yml
> +        res: isHigherHigher
These two check should be moved below the next if, as they won't be used if the condition fails

2021-03-15 20:01 UTC, laurentfufu commented on jahia/jahia_actions.yml
> +    - if("${globals.isKarafLoginEnabled}" == "true"):
now `isKarafLoginEnabled` is a dict like this:
```json
{"${this}": boolean}
```

2021-03-16 09:38 UTC, Ronan-Gorain approved these changes

2021-03-16 09:38 UTC, merged